### PR TITLE
Make Selenium an optional dependency

### PR DESCRIPTION
**Pull request by marcospgp**
#19

### CODE REVIEW

**Comment by nacimgoura** [comment]
Thanks :wink:

**Comment by marcospgp** [comment]
There's a bit of a downside to this, being that there will be an additional step for users who want to use the Selenium method. I don't see a better way around it though, any ideas?

**Comment by nacimgoura** [comment]
I don't know if it is possible to define which method to use during installation. There is also another method: when the user uses selenium, it is installed at that time.

**Comment by marcospgp** [comment]
> I don't know if it is possible to define which method to use during installation.

I don't think there is, at least without altering the installation commands a little bit. Would end up being the same as installing selenium optionally.

> There is also another method: when the user uses selenium, it is installed at that time.

That is an option, we would have to check if selenium is installed and if not, run the commands. We can keep it listed as an enhancement.

**Comment by nacimgoura** [comment]
Show issue #21

**Pull request merged**
