### PR TITLE
#36 redone the element targets

### PR DESCRIPTION
**Pull request by blackbyte-pl**

### CODE REVIEW

**Comment by blackbyte-pl** [comment]
It is still fragile to any markup changes in instagram, but should do job much longer than classes.
Not user what `mentions` and `views` are as I cannot find such fields so i left it as unresolved tags.

**Comment by nacimgoura** [comment]
You tested with an example?

**Comment by blackbyte-pl** [comment]
I have tested with several different accounts.
I do find a problem with multiple images, but this is not connected to the issue. Sometimes (not always, but always on the same post) it is looping forever, like the right arrow is not clicked at all.

**Comment by nacimgoura** [comment]
I'm asking because the travis script didn't work properly. I'll merge and test it manually afterwards.

**Comment by blackbyte-pl** [comment]
nacimgoura account is private, this might cause the script to hang. Currently there is no good way to exit the script if there is no posts and it's looping infinitely

**Pull request merged**
